employer/urls.py
from django.contrib import admin
from django.urls import path

from employer.views import(
    post_job,
    application,
    dashboard,
    jobs,
    job_detail,
    job_edit,
    job_delete,
    accept_application,
    reject_application,
    add_company,
    view_company,
    edit_company, 
    delete_company,
    profile_view,
    profile_edit
   
)

app_name = "employer"

urlpatterns = [
    path('post_job/company <int:id>', post_job, name='post_job'),
    path('applications/', application, name='applications'),
    path('dashboard/', dashboard, name='dashboard'),
    path('jobs/', jobs, name='jobs'),
    path('jobs/details/job_id <int:job_id>', job_detail, name='job_detail'),
    path('jobs/job_id <int:id>/edit/', job_edit, name='job_edit'),
    path('jobs/delete/', job_delete, name='job_delete'),
    path('accept/application_id <int:id>/', accept_application, name='accept_application'),
    path('reject/application_id <int:id>/', reject_application, name='reject_application'),
    path('add_company/', add_company, name='add_company'),
    path('view_company/', view_company, name='view_company'),
    path('delete_company/', delete_company, name='delete_company'),
    path('edit_company/id <int:id>/', edit_company, name='edit_company'),
    path("profile/user_id  <int:id>/",profile_view, name='profile'),
    path("profile/edit/user_id  <int:id>/",profile_edit, name='profileedit'),


]

jobboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from users.views import(
    login_view,
    signup_view,
    contactus,
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("jobs.urls", namespace="jobs")),
    path('employer/', include("employer.urls", namespace="employer")),
    path('users/', include("users.urls", namespace="user")),
    path('login/',login_view, name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("contact/", contactus, name="contact"),
    path('register/', signup_view, name='register'),
  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Job Board Admin"
admin.site.site_title = "Job Board Admin"

jobs/urls.py
from django.urls import path,include
from jobs.views import(
        job_list, 
        job_detail, 
        apply_job,
        homepage, 
        search_view,
        filter_view,
        # main

       
)

app_name = "jobs"


urlpatterns = [
    path('', homepage, name='index'),
    path('jobs-list', job_list, name='job_list'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/apply/', apply_job, name='apply_job'),
    path('search/', search_view, name="search"),
    path('filter/', filter_view, name="filter_view"),
    # path('recommed/',main,name="main")

]

employer/models.py
from django.db import models
from users.models import User
from django.core.validators import FileExtensionValidator


class Company(models.Model):
    company_name = models.CharField(max_length=255, null=True, blank=True)
    company_website = models.CharField(max_length=255, null=True, blank=True)
    company_location = models.CharField(max_length=255, null=True, blank=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    logo = models.FileField(upload_to='logo/',null=True,blank=True,validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg','svg'])])


    def __str__(self):
        return self.company_name

employer/forms.py
from django import forms
from employer.models import Company
from django.utils import timezone
from django.core.exceptions import ValidationError
from users.models import User

class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        exclude = ('added_by',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["id"] = "exampleFormControlInput1"

    def clean_company_name(self):
        name = self.cleaned_data.get('company_name')
        if name is None:
            raise ValidationError("Company name cannot be empty.")
        return name
    def clean_company_website(self):
        name = self.cleaned_data.get('company_website')
        if name is None:
            raise ValidationError("Company website cannot be empty.")
        return name
    def clean_company_location(self):
        name = self.cleaned_data.get('company_location')
        if name is None:
            raise ValidationError("Company location cannot be empty.")
        return name

    def clean_application_valid(self):
        print("hrtr")
        date = self.cleaned_data.get('application_valid')
        if date < timezone.now().date():
            raise ValidationError("Date cannot be set in past")
        return date
    
class EmployerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ( 
            "first_name",
            "last_name",
            "username",
            "email",
            "image",
            )
       
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control row-4"

jobs/forms.py
from django import forms
from jobs.models import Job, Application
from django.utils import timezone
from django.core.exceptions import ValidationError
from upload_validator import FileTypeValidator, magic



class JobForms(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ("posted_by", "company_name", "location", "company_website", "logo", "company")

        widgets = {
            "application_valid": forms.DateInput(attrs={"type": "date"}),
            "description": forms.Textarea(
                attrs={
                    "rows": 5,
                    "cols": 20,
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def clean_application_valid(self):
        date = self.cleaned_data.get("application_valid")
        if date < timezone.now().date():
            raise ValidationError("Date cannot be set in past")
        return date


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = "__all__"
        widgets = {
            "resume": forms.FileField(
                label="",
                help_text="Only pdf formats are accepted.",
                required=False,
                validators=[
                    FileTypeValidator(
                        allowed_types=["applcation/pdf"],
                        allowed_extensions=[".pdf"],
                    )
                ],
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["category"]


      


class TypeForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["type"]

class LevelForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["level"]

class SalaryForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["salary"]

employer/views.py
from django.db.models import Q
from django.shortcuts import render,redirect, get_object_or_404
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required, user_passes_test
from jobs.models import Job, Application, Message
from employer.models import Company
from jobs.forms import JobForms
from employer.forms import EmployerForm
from employer.forms import CompanyForm
from users.models import User
from django.utils import timezone



def employer_check(user):
    return user.is_employer
    
def jobseeker_check(user):
    return not user.is_employer
    


@login_required(login_url='login')
@user_passes_test(employer_check, redirect_field_name='jobs:index')
def post_job(request, id):
    id = request.user
    comp = Company.objects.filter(added_by = id)
    if comp:
        company = Company.objects.get(added_by = id)
        form = JobForms(request.POST or None, request.FILES or None)
        if form.is_valid():
            add = form.save(commit=False)
            add.company_name = company.company_name
            add.company_website = company.company_website
            add.location = company.company_location
            add.logo = company.logo
            add.posted_by = request.user
            add.company = company
            # plus = Job(company_name = add.company_name, location = add.company_location, company_website = add.company_website, posted_by_id = request.user)
            add.save()
            messages.success(request, "Job posted successfully")
            return HttpResponseRedirect(reverse ('employer:jobs'))
    else:
        messages.warning(request, "You need to register a company first")
        return HttpResponseRedirect(reverse ('employer:add_company'))
    return render(request, 'post_job.html', {"form":form, "company":company,})

@login_required(login_url="login")
def job_edit(request, id):
    company = Company.objects.filter(added_by = request.user)
    job = get_object_or_404(Job, id=id)
    form = JobForms(request.POST or None, request.FILES or None, instance=job)
    if form.is_valid():
        save = form.save()
        if save:
            messages.success(request, "Job updated successfully")
        else:
            messages.error(request, "Error updating job")
        # return redirect(to='users:profile')
        return HttpResponseRedirect(
            reverse(
                "employer:job_detail",
                args=(job.id,),
            )
        )
    return render(request, "edit_job.html", {"form": form, "job": job, "company":company,})


@login_required(login_url="login")
def job_delete(request):
    jobid = request.POST.get("jobid")
    job = get_object_or_404(Job, id=jobid)
    save = job.delete()
    if save:
        messages.success(request, "Job deleted successfully")
    else:
        messages.error(request, "Error deleting job")
    return HttpResponseRedirect(reverse("employer:jobs"))

@login_required(login_url='login')
@user_passes_test(employer_check)
def add_company(request):
    company = Company.objects.filter(added_by = request.user)
    if company:
        return HttpResponseRedirect(reverse ('employer:dashboard'))
    form = CompanyForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        add = form.save(commit=False)
        add.added_by = request.user
        added = add.save()
        if added:
            messages.success(request, "Company added successfully")
        return HttpResponseRedirect(reverse ('employer:view_company'))
    return render(request, 'addcompany.html', {"form":form})

@login_required(login_url='login')
@user_passes_test(employer_check)
def edit_company(request, id):
    company = Company.objects.get(added_by = request.user, id = id)
    jobs = Job.objects.filter(posted_by = request.user)
    print (jobs)
    form = CompanyForm(request.POST or None, request.FILES or None, instance = company)
    if form.is_valid():
        save = form.save()
        jobs.update(logo=save.logo)
        if save:
            messages.success(request, "Company updated successfully")
        else:
            messages.error(request, "Error updating company")
        return HttpResponseRedirect(reverse ('employer:view_company'))
    return render(request, 'editcompany.html', {"form":form})

@login_required(login_url='login')
@user_passes_test(employer_check)
def view_company(request):
    company = Company.objects.get(added_by = request.user)
    return render(request, 'viewcompany.html', {"company":company})
    

@login_required(login_url="login")
@user_passes_test(employer_check)
def delete_company(request):
    companyid = request.POST.get("companyid")
    company = get_object_or_404(Company, id=companyid)
    company.delete()
    return HttpResponseRedirect(reverse("employer:dashboard"))


@login_required(login_url='login')
@user_passes_test(employer_check)
def application(request):

    jobs = Job.objects.filter(posted_by = request.user)
    company = Company.objects.filter(added_by = request.user)
    print(jobs)
    applications = Application.objects.filter(posted_by = request.user)
    messages = Message.objects.all()
    print(messages)

    
    print(applications)
    return render(
        request,
        "applications.html",
        {"applications":applications,
            "jobs":jobs,
            "company":company,
         
         },
         
    
        )

@login_required(login_url='login')
@user_passes_test(employer_check)
def job_detail(request, job_id):
    company = Company.objects.filter(added_by = request.user)
    jobs = Job.objects.get(id=job_id)
    date = timezone.now().date()
    user = request.user

    return render(
        request, "jobdetails.html", {"jobs": jobs, "date": date, "user":user, "company":company,}
    )


@login_required(login_url='login')
@user_passes_test(employer_check)
def dashboard(request):
    company = Company.objects.filter(added_by = request.user)
    jobs = Job.objects.filter(posted_by = request.user).count()
    applications = Application.objects.filter(posted_by = request.user).count()

    return render(
            request,
            "employer_dashboard.html",
            {
                "company":company,
                "jobs":jobs,
                "applications":applications,
            }
    )
   

@login_required(login_url='login')
@user_passes_test(employer_check)
def jobs(request):
    company = Company.objects.filter(added_by = request.user)
    
    jobs = Job.objects.filter(posted_by = request.user).order_by('-created_at')
    return render(
        request,
        "jobs.html",
        {"jobs":jobs,
        "company":company,
         }

    )

@login_required(login_url='login')
@user_passes_test(employer_check)
def accept_application(request, id):
    applications = Application.objects.get(id = id)
    company = Company.objects.get(added_by = request.user)
    if request.method == "POST":
        message = request.POST.get("message")
        application_id = request.POST.get("application_id")
        company_name = request.POST.get("company_name")
        employer_name = request.POST.get("employer_name")
        applicant_name = request.POST.get("applicant_name")
        status = "Accepted"
        accept = Message( message=message, status = status, application_id=application_id, company_name = company_name, applicant_name = applicant_name, employer_name = employer_name)
        accept.save()
        Application.objects.filter(id = application_id).update(status = status)
        return HttpResponseRedirect(reverse("employer:applications"))
    return render (request, "accept.html", {"applications": applications, "company":company} )

@login_required(login_url='login')
@user_passes_test(employer_check)
def reject_application(request, id):
    applications = Application.objects.get(id = id)
    company = Company.objects.get(added_by = request.user)
    if request.method == "POST":
        message = request.POST.get("message")
        application_id = request.POST.get("application_id")
        company_name = request.POST.get("company_name")
        employer_name = request.POST.get("employer_name")
        applicant_name = request.POST.get("applicant_name")
        status = "Rejected"
        reject = Message( message=message, status = status, application_id=application_id, company_name = company_name, applicant_name = applicant_name, employer_name = employer_name)
        reject.save()
        Application.objects.filter(id = application_id).update(status = status)
        return HttpResponseRedirect(reverse("employer:applications"))
    return render (request, "reject.html", {"applications": applications, "company":company} )


@login_required(login_url = 'login')
def profile_view(request,id):
    company = Company.objects.filter(added_by = request.user)
    user = User.objects.get(id=id)
    return render(
        request,
        "profileview.html",
        {"user":user,
         "company":company,},
    )

@login_required(login_url='login')
def profile_edit(request,id):
    user = get_object_or_404(User,id=id)
    company = Company.objects.filter(added_by = request.user)
    form = EmployerForm(request.POST or None,request.FILES or None, instance = request.user)
    if form.is_valid():
        form.save()
        messages.success(request, "Profile updated successfully")
        return HttpResponseRedirect(
            reverse(
                "employer:profile",
                args=(
                    user.id,
                ),
            )
        )
    return render(request,"profileedit.html",{"form":form, "user":user, "company":company,})

employer/templates/accept.html
{% extends 'employerbase.html' %}

{% block title %}
<title> Accept Application </title>

{% endblock title %}

{% block content %}
{% include 'header.html' %}

{% include 'sidebar.html' %}

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h5">Message</h1>
    </div>
    <form action="#" name="searchfiler" method="post"> {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Applicant Name:</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{applications.name}}"
                name="applicant_name" readonly>
        </div>
        <div class="mb-3">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" placeholder="Enter message"
                name="message"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Company Name:</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{company.company_name}}"
                name="company_name" readonly>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Employer Name:</label>
            <input type="text" class="form-control" id="exampleFormControlInput1"
                value="{{request.user.first_name}} {{request.user.last_name}} " name="employer_name" readonly>
        </div>
        <input type="hidden" value='{{applications.id}}' class="form-control" name="application_id" readonly>

        <div class="mb-3">
            <div class="mb-3" style="text-align: left;">
                <button type="submit" class="btn btn-outline-success"><i class="bi bi-check-lg me-2"></i></i>Accept
                    Application</button>
            </div>
        </div>
    </form>
</main>

{% endblock content %}

employer/templates/jobdetails.html
{% extends 'employerbase.html' %} {% block title %}
<title>Job Detail for {{ jobs.title }}</title>

{% endblock title %} {% block content %}

{% include 'header.html' %}
{% include 'sidebar.html' %}

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="table-responsive mt-3">
    {% include 'flashmessage.html' %}
    <table class="table table-sm" style="text-align: left">
      <tbody>
        <tr>
          <td colspan="2" class="fw-bold" style="text-align: left; font-size: 24px">
            {{ jobs.title }}
          </td>
        </tr>
        <tr>
          <th>Description</th>
          <td style="text-align: justify">{{jobs.description}}.</td>
        </tr>
        <tr>
          <th>Salary</th>
          <td style="text-align: justify">{{jobs.salary}}</td>
        </tr>
        <tr>
          <th>Job Type</th>
          <td style="text-align: justify">{{jobs.type}}</td>
        </tr>
        <tr>
          <th>Catagory</th>
          <td style="text-align: justify">{{jobs.category }}</td>
        </tr>
        <tr>
          <th>Level</th>
          <td style="text-align: justify">{{jobs.level}}</td>
        </tr>
        <tr>
          <th>No of Openings</th>
          <td style="text-align: justify">{{jobs.no_of_openings}}</td>
        </tr>
        <tr>
          <th>Posted On</th>
          <td style="text-align: justify">{{jobs.created_at}}</td>
        </tr>
        <tr>
          <th>Valid Till</th>
          <td style="text-align: justify">{{jobs.application_valid}}</td>
        </tr>
        <tr></tr>
        <tr>
          <th style="text-align: justify;">Action</th>
          <td colspan="2" style="text-align: justify">
            <a href="{% url 'employer:job_edit' jobs.id %}">
              <button type="button" class="btn btn-success btn-sm px-3 me-3">
                <i class="bi bi-pencil-square pe-2"></i>Edit
              </button></a>
            <button type="button" class="btn btn-danger btn-sm px-3" data-jobid="{{jobs.id}}" data-bs-toggle="modal"
              data-bs-target="#exampleModal">
              <i class="bi bi-trash pe-2"></i>Delete
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</main>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Job</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are You Sure?
        <form id="delete-form" method="post" action="{% url 'employer:job_delete' %}">
          {%csrf_token%}
          <input type="hidden" name="jobid" id="_jobid" />
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          No
        </button>
        <button type="button" class="btn btn-danger btn-md" id="delete-button">
          Yes
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block script%} {{ block.super }}
<script type="text/javascript">
  $(document).ready(function () {
    $.ajax({
      url: "/demo-for-ajax/",
      type: "GET",
      dataType: "json",
      success: function (res) {
        console.log(res);
      },
      error: function (res) {
        console.log(res);
      },
    });
    let modal = document.getElementById("exampleModal");
    modal.addEventListener("show.bs.modal", function (evt) {
      let btn = evt.relatedTarget;
      let jobid = btn.dataset.jobid;
      $("#_jobid").val(jobid);
    });

    $("#delete-button").click(function () {
      $("#delete-form").submit();
    });
  });

  //    function handleurl(url){
  //     url=document.getElementById("url")
  //     window.open(url)
  //    }
</script>
{% endblock script %}

employer/templates/sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-body-tertiary sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column" style="font-size: 16px;">
            <li class="nav-item" style="font-size: 24px; font-weight: 600;">
                <p class="nav-link" href="" style="color: black;">
                    Dashboard
                </p>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:dashboard' %}" style="color: black;">
                    <i class="bi bi-house-door"></i>
                    Home
                </a>
            </li>
            <li class="nav-item" style="background-color:#B6C6FF; border-radius: 25px;"
                onmouseover="this.style.backgroundColor='#8ca3f5';" onmouseout="this.style.backgroundColor='#B6C6FF';">
                <a class="nav-link" href="{% url 'employer:post_job' user.id %}" style="color: black;">
                    <i class="bi bi-plus-circle"></i>
                    Post a Job
                </a>
            </li>
            {% if not company %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:add_company' %}" style="color: black;"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">
                    <i class="bi bi-building-add"></i>
                    Register Company
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:view_company' %}" style="color: black;"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">
                    <i class="bi bi-building-add"></i>
                    View Company
                </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:jobs' %}" style="color: black;"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">
                    <i class="bi bi-briefcase"></i>
                    Job Listings
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:profile' user.id %}" style="color: black;"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">
                    <i class="bi bi-person-circle"></i>
                    View Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employer:applications' %}" style="color: black;"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">
                    <i class="bi bi-envelope"></i>
                    View Applications
                </a>
            </li>
        </ul>
    </div>
</nav>

employer/templates/viewcompany.html
{% extends 'employerbase.html' %}
{% block title %}
<title>View Company</title>

{% endblock title %}
{% load static %}


{% block content %}

{% include 'header.html' %}

{% include 'sidebar.html' %}

{% if company %}

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mb-2">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h5">Company Profile</h1>
    </div>
    {% include 'flashmessage.html' %}

    {% if company.logo %}
    <img class="img-fluid rounded mt-3" src="{{company.logo.url}}" alt="profile" width="150px" height="120px"></img>
    {% else %}
    <img class="img-fluid rounded mt-3" src="{% static 'blank.png' %}" alt="profile" width="150px" height="120px"></img>
    {% endif %}
    <div class="table-responsive mt-5">
        <table class="table table-sm" style="text-align: left; width: auto; height: 1vh;">
            <tbody>
                <tr>
                    <th>Company Name </th>
                    <td style="text-align: justify;">{{company.company_name}}</td>
                </tr>
                <tr>
                    <th>Address </th>
                    <td style="text-align: justify;">{{company.company_location}}</td>
                </tr>
                <tr>
                    <th>Website </th>
                    <td style="text-align: justify;">{{company.company_website}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="mb-3">
        <div class="mb-3" style="text-align: left;">
            <a href="{% url 'employer:edit_company' company.id %}" style="text-decoration: none;"> <button class="px-4"
                    style="background-color: #B6C6FF; 
                border-radius: 5px; border:none; height: 4vh; width:auto;">
                    <i class="bi bi-pencil-square pe-2"></i>Edit</button>

            </a>
            <button class="px-4" type="submit" value="submit" style="background-color: #DC3545; color:white; 
            border-radius: 5px; border:none; height: 4vh; width:auto;" data-companyid="{{company.id}}"
                data-bs-toggle="modal" data-bs-target="#exampleModal">
                <i class="bi bi-trash pe-2"></i>Delete</button>
        </div>
    </div>
</main>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Company</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="fw-normal">Are You Sure?</p>
                <p class="fw-small">The Jobs you have posted will be deleted too.</p>
                <form id="delete-form" method="post" action="{% url 'employer:delete_company' %}">
                    {%csrf_token%}
                    <input name="companyid" id="_companyid" type="hidden" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    No
                </button>
                <button type="button" class="btn btn-danger btn-md" id="delete-button">
                    Yes
                </button>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock content %}
{% block script%} {{ block.super }}
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            url: "/demo-for-ajax/",
            type: "GET",
            dataType: "json",
            success: function (res) {
                console.log(res);
            },
            error: function (res) {
                console.log(res);
            },
        });
        let modal = document.getElementById("exampleModal");
        modal.addEventListener("show.bs.modal", function (evt) {
            let btn = evt.relatedTarget;
            let companyid = btn.dataset.companyid;
            $("#_companyid").val(companyid);
        });

        $("#delete-button").click(function () {
            $("#delete-form").submit();
        });
    });

    //    function handleurl(url){
    //     url=document.getElementById("url")
    //     window.open(url)
    //    }
</script>
{% endblock script %}