jobboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from users.views import(
    login_view,
    signup_view,
    contactus,
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("jobs.urls", namespace="jobs")),
    path('employer/', include("employer.urls", namespace="employer")),
    path('users/', include("users.urls", namespace="user")),
    path('login/',login_view, name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("contact/", contactus, name="contact"),
    path('register/', signup_view, name='register'),
  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Job Board Admin"
admin.site.site_title = "Job Board Admin"

jobs/urls.py
from django.urls import path,include
from jobs.views import(
        job_list, 
        job_detail, 
        apply_job,
        homepage, 
        search_view,
        filter_view,
        # main

       
)

app_name = "jobs"


urlpatterns = [
    path('', homepage, name='index'),
    path('jobs-list', job_list, name='job_list'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/apply/', apply_job, name='apply_job'),
    path('search/', search_view, name="search"),
    path('filter/', filter_view, name="filter_view"),
    # path('recommed/',main,name="main")

]

jobs/models.py
from ast import mod
from tkinter import N
from turtle import bk, mode
from django.db import models
from users.models import User
from django.core.validators import FileExtensionValidator
from employer.models import Company


class Salary(models.TextChoices):
    NONE = "None", "Select Salary Range"
    FIRST = "10000-20000","10000-20000"
    SECOND = "20000-30000","20000-30000"
    THIRD = "30000-40000","30000-40000"
    FOURTH = "40000-50000","40000-50000"
    FIFTH = "50000-60000","50000-60000"
    SIXTH = "60000-70000","60000-70000"
    SEVENTH = "70000-80000","70000-80000"
    EIGHTH = "80000-90000","80000-90000"
    NINTH = "90000-100000","90000-100000"

class Category(models.TextChoices):

    NONE = "None", "Select One Category"
    FREELANCER = "Free Lancer","Free Lancer"
    PARTTIME = "Part Time","Part Time"
    FULLTIME = "Full Time", "Full Time"
    INTERN = "Intern", "Intern"
    TEMPORARY = "Temporary", "Temporary"
    CONTRACT = "Contract", "Contract"

class Level(models.TextChoices):
    NONE = "None", "Select One Level"
    ENTRY = "Entry","Entry"
    MID = "Mid","Mid"
    SENIOR = "Senior", "Senior"
    MANAGER = "Manager", "Manager"


class Type(models.TextChoices):
    NONE = "None", "Select One Type"
    TEACHER = "Teacher","Teacher"
    IT = "IT","IT"
    COMPUTERPROGRAMMER = "Computer Programmer", "Computer Programmer"
    GRAPHICSDESIGNER = "Graphics Designer", "Graphics Designer"
    WEBDEVELOPER ="Web Developer","Web Developer"
    DATABASEADMINISTRATOR ="Database Administrator","Database Administrator"
    TECHNICIAN ="Technician","Technician"
    ACCOUNTANT ="Accountant","Accountant"
    SOFTWAREDEVELOPER="Software Developer","Software Developer"
    WEBDESIGNER="Web Designer","Web Designer"
    HARDWAREENGINEER="Hardware Engineer","Hardware Engineer"
    NETWORKADMINISTRATOR="Network Administrator","Network Administrator"
    HARDWAREARCHITECT="Hardware Architect","Hardware Architect"
    DATAANALYST="Data Analyst","Data Analyst"
    SYSTEMADMINISTRATOR="System Administrator","System Administrator"
    COMPUTERSCIENTIST="Computer Scientist","Computer Scientist"
    SOFTWAREENGINEER="Software Engineer","Software Engineer"
    SYSTEMSECURITY="System Securtiy","System Securtiy"
    MOBILEAPPLICATIONDEVELOPER="Mobile Application Developer","Mobile Application Developer"
    GAMEDESIGNER="Game Designer","Game Designer"
    GAMEDEVELOPER="Game Developer","Game Developer"
    VISUALDEVELOPER="Visual Developer","Visual Developer"
    NETWORKANALYST="Network Analyst","Network Analyst"
    NETWORKMANAGER="Network Manager","Network Manager"
    NETWORKDESIGNER="Network Designer","Network Designer"
    NETWORKENGINEER="Network Engineer","Network Engineer"
    SOFTWARETESTER="Software Tester","Software Tester"
    DATASCIENTIST="Data Scientist","Data Scientist"
    DATAARCHITECT="Data Architect","Data Architect"
    SOFTWAREARCHITECT="Software Architect","Software Architect"
    INFORMATIONARCHITECT="Information Architect","Information Architect"
    STATISTICALPROGRAMMER="Statistical Programmer","Statistical Programmer"
    ITINSTRUCTOR="IT Instructor","IT Instructor"
    TEXTUREARTIST="Texture Artist","Texture Artist"
    TECHNICALARTIST="Technical Artist","Technical Artist"
    GAMEDIRECTOR="Game Director","Game Director"
    GAMEPRODUCER="Game Producer","Game Producer"
    ANIMATOR="Animator","Animator"
    ANIMATIONSUPERVISOR="animationsupervisor","Animation Supervisor"
    ITMANAGER="Animation Supervisor","IT Manager"
    WEBMASTER="Web Master","Web Master"
    WENEDITOR="Web Editor","Web Editor"
    CONTENTMANAGER="Content Manager","Content Manager"
    CINEMATICARTIST="Cinematic Artist","Cinematic Artist"
    CHARACTERDESIGNER="Character Designer","Character Designer"
    SUPERVISOR="Supervisor","Supervisor"
    PROFESSIONALGAMER="Profesional Gamer","Profesional Gamer"


class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    company_name = models.CharField(max_length=200, null=True, blank=True)
    company_website = models.CharField(max_length=200, null=True, blank=True)
    logo = models.FileField(upload_to='logo/',null=True,blank=True,validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])
    location = models.CharField(max_length=201, null=True, blank=True)
    no_of_openings = models.PositiveIntegerField()
    salary = models.CharField(choices=Salary.choices,default=None,max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    application_valid = models.DateField()
    category = models.CharField(choices=Category.choices,default=None)
    type = models.CharField(choices=Type.choices,default=None)
    level = models.CharField(choices=Level.choices,default=None)
    modified_at = models.DateField(auto_now=True)
    posted_by = models.ForeignKey(User,on_delete= models.CASCADE)
    company = models.ForeignKey(Company,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.title
    


class Status(models.TextChoices):
    PENDING = "Pending","Pending"
    ACCEPTED = "Accepted","Accepted"
    REJECTED = "Rejected", "Rejected"


class Application(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255,null=True, blank=True)
    resume = models.FileField(upload_to='resume/',null=True,blank=True,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    submitted_on = models.DateField(auto_now=True)
    posted_by = models.CharField(max_length=200, null=True, blank=True)
    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    submitted_for = models.ForeignKey(Job,on_delete=models.CASCADE) 
    status = models.CharField(choices=Status.choices,default=Status.PENDING)

    def __str__(self):
        return self.submitted_for.title
    

class Message(models.Model):
    message = models.CharField(max_length=1055, null=True, blank=True)
    status = models.CharField(choices=Status.choices, default=Status.PENDING )
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255, null=True, blank=True)
    applicant_name = models.CharField(max_length=255, null=True, blank=True)
    employer_name = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.status
    







      
    
        

jobs/forms.py
from django import forms
from jobs.models import Job, Application
from django.utils import timezone
from django.core.exceptions import ValidationError
from upload_validator import FileTypeValidator, magic



class JobForms(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ("posted_by", "company_name", "location", "company_website", "logo", "company")

        widgets = {
            "application_valid": forms.DateInput(attrs={"type": "date"}),
            "description": forms.Textarea(
                attrs={
                    "rows": 5,
                    "cols": 20,
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def clean_application_valid(self):
        date = self.cleaned_data.get("application_valid")
        if date < timezone.now().date():
            raise ValidationError("Date cannot be set in past")
        return date


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = "__all__"
        widgets = {
            "resume": forms.FileField(
                label="",
                help_text="Only pdf formats are accepted.",
                required=False,
                validators=[
                    FileTypeValidator(
                        allowed_types=["applcation/pdf"],
                        allowed_extensions=[".pdf"],
                    )
                ],
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["category"]


      


class TypeForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["type"]

class LevelForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["level"]

class SalaryForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["salary"]

jobs/views.py
import re
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from jobs.models import Job, Application
from django.utils import timezone
from jobs.forms import CategoryForm, TypeForm, LevelForm, SalaryForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')
    
def job_similar(job, top_n=5):
    try:
        # Preprocess and vectorize the text data
        category = job.category
        level = job.level
        type = job.type
        

        # jobs = models.job.objects.exclude(pk=job.pk, category=category)
        jobs = Job.objects.filter(Q(category__contains = category) | Q(level__contains = level) | Q(type__contains = type) ).exclude(pk=job.pk)
        texts = [
            job.title + " " + job.description + " " + job.level
            for job in jobs
        ]
        vectorizer = TfidfVectorizer()
        feature_vectors = vectorizer.fit_transform(texts)

        # Calculate similarity scores
        job_vector = vectorizer.transform(
            [job.title + " " + job.description + " " + job.level]
        )
        similarity_scores = cosine_similarity(job_vector, feature_vectors).flatten()
        print (similarity_scores)

        # Get the indices of the top similar jobs
        top_indices = similarity_scores.argsort()[::-1][:top_n]

        # Retrieve the top similar jobs
        similar_jobs = [jobs[idx] for idx in top_indices.tolist()]
        print(similar_jobs)
        return similar_jobs
        
    except ValueError as e:
        print(str(e))
        return []
    

def jobseeker_check(user):
    return not user.is_employer


def homepage(request):
    applications = Application.objects.all().count()
    print(applications)
    jobs = Job.objects.order_by("-created_at")[:6]
    return render(request, "index.html", {"jobs": jobs, "applications": applications})



def job_list(request):
    category = CategoryForm(request.POST or None)
    type = TypeForm(request.POST or None)
    level = LevelForm(request.POST or None)
    salary = SalaryForm(request.POST or None)
    date = timezone.now().date()
    jobs = Job.objects.all().order_by("-created_at")
    paginator = Paginator(jobs,per_page = 10)
    page_number = request.GET.get("page")
    try:
        page_obj = paginator.get_page(
            page_number
        )  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = paginator.page(paginator.num_pages)
   
    return render(
        request, "job_list.html", {"jobs": page_obj, "date": date, "category": category, "type": type, "level": level, "salary": salary}
    )
    
@login_required()
@user_passes_test(jobseeker_check)
def job_detail(request, job_id):
    jobs = Job.objects.get(id=job_id)
    all = Job.objects.order_by("-created_at")[:6]
    date = timezone.now().date()
    user = request.user
    applications = Application.objects.filter(submitted_by=user, submitted_for=jobs)
    similar_jobs = job_similar(jobs, top_n=5)

    return render(
        request, "details.html", {"jobs": jobs, "applications": applications, "all": all, "date": date, "similar_jobs": similar_jobs}
    )




@login_required(login_url="login")
@user_passes_test(jobseeker_check)
def apply_job(request, job_id):
    jobs = Job.objects.get(id=job_id)
    user = request.user
    resume = user.resume
    # if request.method == "POST":
    if resume:
        name = user.first_name + " " + user.last_name
        email = user.email
        submitted_for_id = jobs.id
        submitted_by_id = user.id
        applicant = Application(
            name=name,
            email=email,
            submitted_for_id=submitted_for_id,
            submitted_by_id=submitted_by_id,
            posted_by=jobs.posted_by,
            resume=resume,
        )
        apply = applicant.save()
        if apply:
            messages.success(request, "You have successfully applied for this job")
            
    else:
        messages.warning(request, "Please upload your resume first")
        return HttpResponseRedirect(reverse("users:profileedit", args=(user.id,)))
    return HttpResponseRedirect(reverse("users:application_view"))
    # return render(request, "job_apply.html", {"job": jobs})


def search_view(request):
    categoryform = CategoryForm(request.POST)
    typeform = TypeForm(request.POST)
    levelform = LevelForm(request.POST)
    salaryform = SalaryForm(request.POST) 
    if request.method == "POST":
        searchtext = request.POST["searchtext"]
        print(searchtext)
        searchresult = Job.objects.filter(
            Q(title__contains=searchtext)
            | Q(company_name__contains=searchtext)
            | Q(location__contains=searchtext)
            | Q(category__contains=searchtext)    
            | Q(type__contains=searchtext)    
            | Q(level__contains=searchtext)    

                
        )
        paginator = Paginator(searchresult, per_page=4)
        page_number = request.GET.get("page")
        try:
            page_obj = paginator.get_page(
                page_number
            )  # returns the desired page object
        except PageNotAnInteger:
            # if page_number is not an integer then assign the first page
            page_obj = paginator.page(1)
        except EmptyPage:
            # if page is empty then return last page
            page_obj = paginator.page(paginator.num_pages)
        return render(
            request, "search.html", {"searchtext": searchtext, "jobs": page_obj, "category": categoryform, "type": typeform, "level": levelform, "salary": salaryform}
        )
    return render(request, "search.html")


def filter_view(request):
    print("hello")
    categoryform = CategoryForm(request.POST)
    typeform = TypeForm(request.POST)
    levelform = LevelForm(request.POST)
    salaryform = SalaryForm(request.POST)
    if request.method == "POST":
        category = request.POST["category"]
        type = request.POST["type"]
        level = request.POST["level"]
        salary = request.POST["salary"]
        filterjob = Job.objects.filter(
            Q(category__contains=category)
            | Q(type__contains=type)
            | Q(level__contains=level)
            | Q(salary__contains=salary)
        )

     
        return render(request, "filter.html", {"jobs": filterjob, "category": categoryform, "type": typeform, "level": levelform, "salary": salaryform})
    return render(request, "filter.html")

jobs/templates/filter.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% load static %}

{% block title %}
<title> Job Filter </title>

{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static 'staticfiles/css/joblist.css' %}">
<section class="jobsearch" style="background-color: #DEDFE0;">

    <div class="container mt-4" id="searchfilter">
        <form action="{% url 'jobs:filter_view' %}" name="searchfilter" method="post"> {% csrf_token %}
            <div class="container" id="searchcardcontainer">
                <div class="dropdown" name="dropdown">
                    {% for field in category %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in type %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in level %}
                    {{ field }}
                    {% endfor %}
                </div>

                <div class="dropdown" name="dropdown">
                    {% for field in salary %}
                    {{ field }}
                    {% endfor %}
                </div>


                <div class="filterbutton">
                    <a href="{% url 'jobs:job_list' %}" style=" background-color: #F5f5f7; text-decoration: none;">
                        <button type="button">
                            Clear</button></a>
                    <button type="submit" value="submit">Filter<img class="ms-1" src="{% static 'filter.png' %}"
                            width="18px" height="15px"></button>
                </div>
            </div>
        </form>
    </div>
</section>


{% if jobs %}


<section class="card">
    <div class="container" style="display: inline-block;">

        <div class="container" id="cardcontainer">
            {% for job in jobs %}


            <div id="cardbox">
                <a href="{% url 'jobs:job_detail' job.id %}" style="display: block; text-decoration: none;">

                    {% if job.logo %}
                    <div class="card flex-row"><img class="card-img-left example-card-img-responsive"
                            src="{{job.logo.url}}" width="190px" height="200px" alt="" />

                        {% else %}

                        <div class="card flex-row"><img class="card-img-left example-card-img-responsive"
                                src="{% static 'empty.jpg' %}" width="190px" height="200px" alt="" />
                            {% endif %}

                            <div class="card-body">
                                <h4 class="fw-bold fs-5" style="color: #0d1e5c;"> {{job.title}} </h4>
                                <h5 class="fw-bolder fs-6"> Company :{{job.company_name}} </h5>
                                <h5 class="fw-normal fs-6"> Category: {{job.category}} </h5>
                                <h5 class="fw-normal fs-6"> Level: {{job.level}} </h5>
                                <h5 class="fw-normal fs-6"> Type: {{job.type}} </h5>
                                <p><small>Valid Till: {{ job.application_valid}}</small></p>

                            </div>
                        </div>
                </a>
            </div>

            {% endfor %}

        </div>
        <div class="container my-3 ml-1" style="display: flex; justify-content: space-between;">
            {% if jobs.has_previous %}
            <a href="?page={{jobs.previous_page_number}}"><button type="button" class="btn btn-secondary btn-sm px-4">
                    <i class="bi bi-arrow-left me-2"></i>Previous</button></a>
            {% endif %}

            {% if jobs.has_next %}
            <a href="?page={{jobs.next_page_number}}"><button type="button" class="btn btn-secondary btn-sm px-4">
                    Next<i class="bi bi-arrow-right ms-2"></i></button></a>
            {% endif %}
        </div>
    </div>
</section>

{% else %}

<section class="card">
    <div class="container" style="display: inline-block; height: 40vh;">

        <div class="container" id="cardcontainer">


            <div id="cardbox">



                <div class="card-body">

                    <h5 class="fw-normal">Job with your filter is not available</h5>

                </div>

            </div>



        </div>
    </div>
</section>

{% endif %}
{% include 'footer.html' %}

{% endblock content %}

jobs/templates/job_list.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% load static %}
{% block title %}
<title>Job Lists</title>
{% endblock title %}


{% block content %}

<link rel="stylesheet" href="{% static 'staticfiles/css/joblist.css' %}">

<section class="jobsearch" style="background-color: #DEDFE0;">

    <div class="container mt-4" id="searchfilter">
        <form action="{% url 'jobs:filter_view' %}" name="searchfilter" method="post"> {% csrf_token %}
            <div class="container" id="searchcardcontainer">
                <div class="dropdown" name="dropdown">
                    {% for field in category %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in type %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in level %}
                    {{ field }}
                    {% endfor %}
                </div>

                <div class="dropdown" name="dropdown">
                    {% for field in salary %}
                    {{ field }}
                    {% endfor %}
                </div>


                <div class="filterbutton">
                    <a href="{% url 'jobs:job_list' %}" style=" background-color: #F5f5f7; text-decoration: none;">
                        <button type="button">
                            Clear</button></a>
                    <button type="submit" value="submit">Filter<img class="ms-1" src="{% static 'filter.png' %}"
                            width="18px" height="15px"></button>
                </div>
            </div>
        </form>
    </div>
</section>

{% if jobs %}

<section class="card">
    <div class="container" style="display: inline-block;">

        <div class="container" id="cardcontainer">
            {% for job in jobs %}
            {% if job.application_valid >= date %}

            <div id="cardbox">
                <a href="{% url 'jobs:job_detail' job.id %}" style="display: block; text-decoration: none;">

                    {% if job.logo %}
                    <div class="card flex-row"><img class="card-img-left example-card-img-responsive"
                            src="{{job.logo.url}}" width="190px" height="200px" alt="" />
                        {% else %}
                        <div class="card flex-row"><img class="card-img-left example-card-img-responsive"
                                src="{% static 'empty.jpg' %}" width="190px" height="200px" alt="" />
                            {% endif %}
                            <div class="card-body">
                                <h4 class="fw-bold fs-5" style="color: black;"> {{job.title}} </h4>
                                <h5 class="fw-bolder fs-6" style="color: black;"> Company :{{job.company_name}} </h5>
                                <h5 class="fw-normal fs-6" style="color: black;"> Category: {{job.category}} </h5>
                                <h5 class="fw-normal fs-6" style="color: black;"> Level: {{job.level}} </h5>
                                <h5 class="fw-normal fs-6" style="color: black;"> Type: {{job.type}} </h5>
                                <p style="color: black;"><small>Valid Till: {{ job.application_valid}}</small></p>
                            </div>
                        </div>
                </a>

            </div>
            {% endif %}
            {% endfor %}

        </div>
        <div class="container my-3 ml-1" style="display: flex; justify-content: space-between;">
            {% if jobs.has_previous %}
            <a href="?page={{jobs.previous_page_number}}"><button type="button" class="btn btn-secondary btn-sm px-4">
                    <i class="bi bi-arrow-left me-2"></i>Previous</button></a>
            {% endif %}

            {% if jobs.has_next %}
            <a href="?page={{jobs.next_page_number}}"><button type="button" class="btn btn-secondary btn-sm px-4">
                    Next<i class="bi bi-arrow-right ms-2"></i></button></a>
            {% endif %}
        </div>
    </div>
</section>



{% endif %}


{% include 'footer.html' %}
{% endblock content %}

jobs/templates/recommend.html
<style>
    a {
        display: block;
        text-decoration: none;
    }
</style>


<div class="col-md-5 col-lg-4 order-md-last"
    style="border: 0.1px solid #bfc3cb; border-radius: 10px; background-color: #f5f5f7; height: auto;">
    <h4 class="h5  mb-3 py-3" style="border-bottom: 0.1px solid #B6C6FF; text-align: center;">
        Similar Jobs
    </h4>

    {% for job in similar_jobs %}
    {% if job.application_valid >= date %}
    <a href="{% url 'jobs:job_detail' job.id %}">

        <div id="cardbox" class="mb-3" style="border-bottom: 0.1px solid lightslategray">
            <div class="card flex-row"><img class="card-img-left example-card-img-responsive mt-2"
                    src="{{job.logo.url}}" width="100px" height="100px" />
                <div class="card-body" style="text-align: left;">
                    <h4 class="" style="color: #0d1e5c; font-size: 16px;">{{ job.title }}</h4>
                    <h5 class="" style="font-size: 14px;">Company: {{ job.company_name }}</h5>
                    <h5 class="fw-normal fs-6"> Category: {{job.category}} </h5>
                    <h5 class="fw-normal fs-6"> Level: {{job.level}} </h5>
                    <h5 class="fw-normal fs-6"> Type: {{job.type}} </h5>


                </div>
            </div>
        </div>

    </a>
    {% endif %}
    {% endfor %}

</div>

jobs/templates/search.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'staticfiles/css/joblist.css' %}">

<section class="jobsearch" style="background-color: #DEDFE0;">

    <div class="container mt-4" id="searchfilter">
        <form action="{% url 'jobs:filter_view' %}" name="searchfiler" method="post"> {% csrf_token %}
            <div class="container" id="searchcardcontainer">
                <div class="dropdown" name="dropdown">
                    {% for field in category %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in type %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in level %}
                    {{ field }}
                    {% endfor %}
                </div>
                <div class="dropdown" name="dropdown">
                    {% for field in salary %}
                    {{ field }}
                    {% endfor %}
                </div>


                <div class="filterbutton">
                    <a href="{% url 'jobs:job_list' %}" style=" background-color: #F5f5f7; text-decoration: none;">
                        <button type="button">
                            Clear</button></a>
                    <button type="submit" value="submit">Filter<img class="ms-1" src="{% static 'filter.png' %}"
                            width="18px" height="15px"></button>
                </div>
            </div>
        </form>
    </div>
</section>

{% if searchtext %}


{% if jobs %}
<section class="card">
    <div class="container" style="display: inline-block;">

        <div class="container" id="cardcontainer">

            {% for job in jobs %}

            <div id="cardbox">
                <a href="{% url 'jobs:job_detail' job.id %}" style="display: block; text-decoration: none;">

                    <div class="card flex-row"><img class="card-img-left example-card-img-responsive"
                            src="{{job.logo.url}}" width="190px" height="200px" alt="" />

                        <div class="card-body">
                            <h4 class="fw-bold fs-5" style="color: #0d1e5c;"> {{job.title}} </h4>
                            <h5 class="fw-bolder fs-6"> Company :{{job.company_name}} </h5>
                            <h5 class="fw-normal fs-6"> Category: {{job.category}} </h5>
                            <h5 class="fw-normal fs-6"> Level: {{job.level}} </h5>
                            <h5 class="fw-normal fs-6"> Type: {{job.type}} </h5>
                            <p><small>Valid Till: {{ job.application_valid}}</small></p>

                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>
    </div>

</section>
{% else %}
<section class="card">
    <div class="container" style="display: inline-block;">

        <div class="container" id="cardcontainer">

            <div id="cardbox">

                <div class="card-body">

                    <h5 class="fw-normal">Job with your search text {{searchtext}} is not available</h5
                        class="fw-normal fs-6">

                </div>

            </div>



        </div>
    </div>
</section>
{% endif %}


{% else %}
<section class="card">
    <div class="container" style="display: inline-block;">

        <div class="container" id="cardcontainer">

            <div id="cardbox">

                <div class="card-body">

                    <h5 class="fw-normal">Enter something to search for jobs</h5 class="fw-normal fs-6">

                </div>

            </div>



        </div>
    </div>
</section>
{% endif %}
{% include 'footer.html' %}

{% endblock %}